name: "Create a release"

description: "Creates a release"

inputs:
  github-token:
    description: "GitHub token of a user with permission to create a release"
    required: true
  release-draft:
    description: "true to create a draft (unpublished) release, false to create a published one"
    required: true
    default: 'false'
  release-prerelease:
    description: "true to identify the release as a prerelease, false to identify the release as a full release"
    required: true
    default: 'false'

runs:
  using: "composite"

  steps:
    - name: "Determine tag"
      if: "${{ github.event_name }} == 'push' && ${{ github.ref_type }} == 'tag'"
      run: "echo \"RELEASE_TAG=${GITHUB_REF#refs/tags/}\" >> $GITHUB_ENV"
      shell: bash

    - run: bash ./release-create.sh ${{ inputs.release-draft }} ${{ inputs.release-prerelease }}
      shell: bash
      env:
        GITHUB_TOKEN: ${{ secrets.github-token }}
        RELEASE_TAG: ${{ env.RELEASE_TAG }}
